manuals:

  - chainId: 1
    address: '0xBe53A109B494E5c9f97b9Cd39Fe969BE68BF6204'
    label: 'vault'
    defaults: {
      erc4626: true,
      v3: true,
      yearn: true,
      origin: 'yearn',
      apiVersion: '3.0.2',
      registry: '0xff31A1B020c868F6eA3f61Eb953344920EeCA3af',
      asset: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      decimals: 6,
      inceptBlock: 19419991,
      inceptTime: 1710258455
    }
