
cron:
  name: AbiFanout
  queue: fanout
  job: abis
  schedule: '*/15 * * * *'
  start: false

abis:
  - abiPath: 'yearn/3/vault'
    sources: [
      { chainId: 42161, address: '0x252b965400862d94BDa35FeCF7Ee0f204a53Cc36', inceptBlock: 358476628 }
    ]
